#!/usr/bin/env python3

import re

example_input = """
Time:      7  15   30
Distance:  9  40  200
"""

def parse(inp):
    for line in inp.splitlines():
        if line.startswith("Time:"):
            times = re.findall(r"\d+", line)
        if line.startswith("Distance:"):
            distances = re.findall(r"\d+", line)
    return zip(times, distances)

def race(time, record):
    n = 0
    for t in range(1, time):
        s = (time - t) * t
        if s > record:
            n += 1
    return n
assert(race(7, 9)) == 5

def multi(times, records):
    for time, record in zip(times, records):
        n = 
