#!/usr/bin/env python3

example_input = """
???.### 1,1,3
.??..??...?##. 1,1,3
?#?#?#?#?#?#?#? 1,3,1,6
????.#...#... 4,1,1
????.######..#####. 1,6,5
?###???????? 3,2,1
"""

def parse_line(line):
    pat, commas = line.split()
    nums = [int(x) for x in commas.split(',')] 
    return pat+'.', nums

def walk(pat, nums, prefix):
    if not nums:
        if '#' in pat:
            # impossible
            return
    if re.search('^[.]+(.*)')

    if re.match('[?#]{' + str(n

assert count("???.### 1,1,3") == 1
assert count(".??..??...?##. 1,1,3") == 4
assert count("?#?#?#?#?#?#?#? 1,3,1,6") == 1
assert count(example_input) == 21

real_input = open('inputs/day12.input.txt').read()

print(count(real_input)) # =>  8120 is too high!
